// Decompiled with JetBrains decompiler
// Type: Scenes.OutGame.Utility.AccessoryUpgradeParameter
// Assembly: Assembly-CSharp, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null
// MVID: 815152EA-6EB1-4874-BFD7-95E0AD7F491D
// Assembly location: C:\r\DummyDll\Assembly-CSharp.dll

using Il2CppDummyDll;
using UnityEngine;

#nullable disable
namespace Scenes.OutGame.Utility
{
  [Token(Token = "0x20032BC")]
  public struct AccessoryUpgradeParameter
  {
    [Token(Token = "0x400D9F7")]
    [FieldOffset(Offset = "0x0")]
    public int initialLife;
    [Token(Token = "0x400D9F8")]
    [FieldOffset(Offset = "0x4")]
    public int limitLife;
    [Token(Token = "0x400D9F9")]
    [FieldOffset(Offset = "0x8")]
    public int initialStrength;
    [Token(Token = "0x400D9FA")]
    [FieldOffset(Offset = "0xC")]
    public int limitStrength;
    [Token(Token = "0x400D9FB")]
    [FieldOffset(Offset = "0x10")]
    public int initialIntelligence;
    [Token(Token = "0x400D9FC")]
    [FieldOffset(Offset = "0x14")]
    public int limitIntelligence;
    [Token(Token = "0x400D9FD")]
    [FieldOffset(Offset = "0x18")]
    public int initialVitality;
    [Token(Token = "0x400D9FE")]
    [FieldOffset(Offset = "0x1C")]
    public int limitVitality;
    [Token(Token = "0x400D9FF")]
    [FieldOffset(Offset = "0x20")]
    public int initialMind;
    [Token(Token = "0x400DA00")]
    [FieldOffset(Offset = "0x24")]
    public int limitMind;
    [Token(Token = "0x400DA01")]
    [FieldOffset(Offset = "0x28")]
    public int initialAgility;
    [Token(Token = "0x400DA02")]
    [FieldOffset(Offset = "0x2C")]
    public int limitAgility;
    [Token(Token = "0x400DA03")]
    [FieldOffset(Offset = "0x30")]
    public int initialDexterity;
    [Token(Token = "0x400DA04")]
    [FieldOffset(Offset = "0x34")]
    public int limitDexterity;
    [Token(Token = "0x400DA05")]
    [FieldOffset(Offset = "0x38")]
    public int initialLucky;
    [Token(Token = "0x400DA06")]
    [FieldOffset(Offset = "0x3C")]
    public int limitLucky;
    [Token(Token = "0x400DA07")]
    [FieldOffset(Offset = "0x40")]
    [SerializeField]
    public int initialPhysicsDefence;
    [Token(Token = "0x400DA08")]
    [FieldOffset(Offset = "0x44")]
    [SerializeField]
    public int limitPhysicsDefence;
    [Token(Token = "0x400DA09")]
    [FieldOffset(Offset = "0x48")]
    [SerializeField]
    public int initialMagicDefence;
    [Token(Token = "0x400DA0A")]
    [FieldOffset(Offset = "0x4C")]
    [SerializeField]
    public int limitMagicDefence;
    [Token(Token = "0x400DA0B")]
    [FieldOffset(Offset = "0x50")]
    [SerializeField]
    public int initialCriticalAvoid;
    [Token(Token = "0x400DA0C")]
    [FieldOffset(Offset = "0x54")]
    [SerializeField]
    public int limitCriticalAvoid;
    [Token(Token = "0x400DA0D")]
    [FieldOffset(Offset = "0x58")]
    public int initialWeight;
    [Token(Token = "0x400DA0E")]
    [FieldOffset(Offset = "0x5C")]
    public int limitWeight;
    [Token(Token = "0x400DA0F")]
    [FieldOffset(Offset = "0x60")]
    public int initialReinforceFire;
    [Token(Token = "0x400DA10")]
    [FieldOffset(Offset = "0x64")]
    public int limitReinforceFire;
    [Token(Token = "0x400DA11")]
    [FieldOffset(Offset = "0x68")]
    public int initialReinforceIce;
    [Token(Token = "0x400DA12")]
    [FieldOffset(Offset = "0x6C")]
    public int limitReinforceIce;
    [Token(Token = "0x400DA13")]
    [FieldOffset(Offset = "0x70")]
    public int initialReinforceThunder;
    [Token(Token = "0x400DA14")]
    [FieldOffset(Offset = "0x74")]
    public int limitReinforceThunder;
    [Token(Token = "0x400DA15")]
    [FieldOffset(Offset = "0x78")]
    public int initialReinforceWind;
    [Token(Token = "0x400DA16")]
    [FieldOffset(Offset = "0x7C")]
    public int limitReinforceWind;
    [Token(Token = "0x400DA17")]
    [FieldOffset(Offset = "0x80")]
    public int initialReinforceLight;
    [Token(Token = "0x400DA18")]
    [FieldOffset(Offset = "0x84")]
    public int limitReinforceLight;
    [Token(Token = "0x400DA19")]
    [FieldOffset(Offset = "0x88")]
    public int initialReinforceDark;
    [Token(Token = "0x400DA1A")]
    [FieldOffset(Offset = "0x8C")]
    public int limitReinforceDark;
    [Token(Token = "0x400DA1B")]
    [FieldOffset(Offset = "0x90")]
    public int initialReinforceSlash;
    [Token(Token = "0x400DA1C")]
    [FieldOffset(Offset = "0x94")]
    public int limitReinforceSlash;
    [Token(Token = "0x400DA1D")]
    [FieldOffset(Offset = "0x98")]
    public int initialReinforceBlow;
    [Token(Token = "0x400DA1E")]
    [FieldOffset(Offset = "0x9C")]
    public int limitReinforceBlow;
    [Token(Token = "0x400DA1F")]
    [FieldOffset(Offset = "0xA0")]
    public int initialReinforcePierce;
    [Token(Token = "0x400DA20")]
    [FieldOffset(Offset = "0xA4")]
    public int limitReinforcePierce;
    [Token(Token = "0x400DA21")]
    [FieldOffset(Offset = "0xA8")]
    public int initialReinforceShot;
    [Token(Token = "0x400DA22")]
    [FieldOffset(Offset = "0xAC")]
    public int limitReinforceShot;
    [Token(Token = "0x400DA23")]
    [FieldOffset(Offset = "0xB0")]
    public int initialReinforceMagic;
    [Token(Token = "0x400DA24")]
    [FieldOffset(Offset = "0xB4")]
    public int limitReinforceMagic;
    [Token(Token = "0x400DA25")]
    [FieldOffset(Offset = "0xB8")]
    public int initialReinforceProvocation;
    [Token(Token = "0x400DA26")]
    [FieldOffset(Offset = "0xBC")]
    public int limitReinforceProvocation;
    [Token(Token = "0x400DA27")]
    [FieldOffset(Offset = "0xC0")]
    public int initialReinforceConfusion;
    [Token(Token = "0x400DA28")]
    [FieldOffset(Offset = "0xC4")]
    public int limitReinforceConfusion;
    [Token(Token = "0x400DA29")]
    [FieldOffset(Offset = "0xC8")]
    public int initialReinforceShakenUp;
    [Token(Token = "0x400DA2A")]
    [FieldOffset(Offset = "0xCC")]
    public int limitReinforceShakenUp;
    [Token(Token = "0x400DA2B")]
    [FieldOffset(Offset = "0xD0")]
    public int initialReinforceCharmed;
    [Token(Token = "0x400DA2C")]
    [FieldOffset(Offset = "0xD4")]
    public int limitReinforceCharmed;
    [Token(Token = "0x400DA2D")]
    [FieldOffset(Offset = "0xD8")]
    public int initialReinforceBerserk;
    [Token(Token = "0x400DA2E")]
    [FieldOffset(Offset = "0xDC")]
    public int limitReinforceBerserk;
    [Token(Token = "0x400DA2F")]
    [FieldOffset(Offset = "0xE0")]
    public int initialReinforceBurned;
    [Token(Token = "0x400DA30")]
    [FieldOffset(Offset = "0xE4")]
    public int limitReinforceBurned;
    [Token(Token = "0x400DA31")]
    [FieldOffset(Offset = "0xE8")]
    public int initialReinforceSleep;
    [Token(Token = "0x400DA32")]
    [FieldOffset(Offset = "0xEC")]
    public int limitReinforceSleep;
    [Token(Token = "0x400DA33")]
    [FieldOffset(Offset = "0xF0")]
    public int initialReinforceParalysis;
    [Token(Token = "0x400DA34")]
    [FieldOffset(Offset = "0xF4")]
    public int limitReinforceParalysis;
    [Token(Token = "0x400DA35")]
    [FieldOffset(Offset = "0xF8")]
    public int initialReinforcePoison;
    [Token(Token = "0x400DA36")]
    [FieldOffset(Offset = "0xFC")]
    public int limitReinforcePoison;
    [Token(Token = "0x400DA37")]
    [FieldOffset(Offset = "0x100")]
    public int initialReinforceDeadlyPoison;
    [Token(Token = "0x400DA38")]
    [FieldOffset(Offset = "0x104")]
    public int limitReinforceDeadlyPoison;
    [Token(Token = "0x400DA39")]
    [FieldOffset(Offset = "0x108")]
    public int initialReinforceBleeding;
    [Token(Token = "0x400DA3A")]
    [FieldOffset(Offset = "0x10C")]
    public int limitReinforceBleeding;
    [Token(Token = "0x400DA3B")]
    [FieldOffset(Offset = "0x110")]
    public int initialReinforceDazzlement;
    [Token(Token = "0x400DA3C")]
    [FieldOffset(Offset = "0x114")]
    public int limitReinforceDazzlement;
    [Token(Token = "0x400DA3D")]
    [FieldOffset(Offset = "0x118")]
    public int initialReinforceDarkness;
    [Token(Token = "0x400DA3E")]
    [FieldOffset(Offset = "0x11C")]
    public int limitReinforceDarkness;
    [Token(Token = "0x400DA3F")]
    [FieldOffset(Offset = "0x120")]
    public int initialReinforcePetrifaction;
    [Token(Token = "0x400DA40")]
    [FieldOffset(Offset = "0x124")]
    public int limitReinforcePetrifaction;
    [Token(Token = "0x400DA41")]
    [FieldOffset(Offset = "0x128")]
    public int initialReinforceDontAction;
    [Token(Token = "0x400DA42")]
    [FieldOffset(Offset = "0x12C")]
    public int limitReinforceDontAction;
    [Token(Token = "0x400DA43")]
    [FieldOffset(Offset = "0x130")]
    public int initialReinforceDontMove;
    [Token(Token = "0x400DA44")]
    [FieldOffset(Offset = "0x134")]
    public int limitReinforceDontMove;
    [Token(Token = "0x400DA45")]
    [FieldOffset(Offset = "0x138")]
    public int initialReinforceDontUseSkill;
    [Token(Token = "0x400DA46")]
    [FieldOffset(Offset = "0x13C")]
    public int limitReinforceDontUseSkill;
    [Token(Token = "0x400DA47")]
    [FieldOffset(Offset = "0x140")]
    public int initialReinforceDoom;
    [Token(Token = "0x400DA48")]
    [FieldOffset(Offset = "0x144")]
    public int limitReinforceDoom;
    [Token(Token = "0x400DA49")]
    [FieldOffset(Offset = "0x148")]
    public int initialResistFire;
    [Token(Token = "0x400DA4A")]
    [FieldOffset(Offset = "0x14C")]
    public int limitResistFire;
    [Token(Token = "0x400DA4B")]
    [FieldOffset(Offset = "0x150")]
    public int initialResistIce;
    [Token(Token = "0x400DA4C")]
    [FieldOffset(Offset = "0x154")]
    public int limitResistIce;
    [Token(Token = "0x400DA4D")]
    [FieldOffset(Offset = "0x158")]
    public int initialResistThunder;
    [Token(Token = "0x400DA4E")]
    [FieldOffset(Offset = "0x15C")]
    public int limitResistThunder;
    [Token(Token = "0x400DA4F")]
    [FieldOffset(Offset = "0x160")]
    public int initialResistWind;
    [Token(Token = "0x400DA50")]
    [FieldOffset(Offset = "0x164")]
    public int limitResistWind;
    [Token(Token = "0x400DA51")]
    [FieldOffset(Offset = "0x168")]
    public int initialResistLight;
    [Token(Token = "0x400DA52")]
    [FieldOffset(Offset = "0x16C")]
    public int limitResistLight;
    [Token(Token = "0x400DA53")]
    [FieldOffset(Offset = "0x170")]
    public int initialResistDark;
    [Token(Token = "0x400DA54")]
    [FieldOffset(Offset = "0x174")]
    public int limitResistDark;
    [Token(Token = "0x400DA55")]
    [FieldOffset(Offset = "0x178")]
    public int initialResistSlash;
    [Token(Token = "0x400DA56")]
    [FieldOffset(Offset = "0x17C")]
    public int limitResistSlash;
    [Token(Token = "0x400DA57")]
    [FieldOffset(Offset = "0x180")]
    public int initialResistBlow;
    [Token(Token = "0x400DA58")]
    [FieldOffset(Offset = "0x184")]
    public int limitResistBlow;
    [Token(Token = "0x400DA59")]
    [FieldOffset(Offset = "0x188")]
    public int initialResistPierce;
    [Token(Token = "0x400DA5A")]
    [FieldOffset(Offset = "0x18C")]
    public int limitResistPierce;
    [Token(Token = "0x400DA5B")]
    [FieldOffset(Offset = "0x190")]
    public int initialResistShot;
    [Token(Token = "0x400DA5C")]
    [FieldOffset(Offset = "0x194")]
    public int limitResistShot;
    [Token(Token = "0x400DA5D")]
    [FieldOffset(Offset = "0x198")]
    public int initialResistMagic;
    [Token(Token = "0x400DA5E")]
    [FieldOffset(Offset = "0x19C")]
    public int limitResistMagic;
    [Token(Token = "0x400DA5F")]
    [FieldOffset(Offset = "0x1A0")]
    public int initialResistProvocation;
    [Token(Token = "0x400DA60")]
    [FieldOffset(Offset = "0x1A4")]
    public int limitResistProvocation;
    [Token(Token = "0x400DA61")]
    [FieldOffset(Offset = "0x1A8")]
    public int initialResistConfusion;
    [Token(Token = "0x400DA62")]
    [FieldOffset(Offset = "0x1AC")]
    public int limitResistConfusion;
    [Token(Token = "0x400DA63")]
    [FieldOffset(Offset = "0x1B0")]
    public int initialResistShakenUp;
    [Token(Token = "0x400DA64")]
    [FieldOffset(Offset = "0x1B4")]
    public int limitResistShakenUp;
    [Token(Token = "0x400DA65")]
    [FieldOffset(Offset = "0x1B8")]
    public int initialResistCharmed;
    [Token(Token = "0x400DA66")]
    [FieldOffset(Offset = "0x1BC")]
    public int limitResistCharmed;
    [Token(Token = "0x400DA67")]
    [FieldOffset(Offset = "0x1C0")]
    public int initialResistBerserk;
    [Token(Token = "0x400DA68")]
    [FieldOffset(Offset = "0x1C4")]
    public int limitResistBerserk;
    [Token(Token = "0x400DA69")]
    [FieldOffset(Offset = "0x1C8")]
    public int initialResistBurned;
    [Token(Token = "0x400DA6A")]
    [FieldOffset(Offset = "0x1CC")]
    public int limitResistBurned;
    [Token(Token = "0x400DA6B")]
    [FieldOffset(Offset = "0x1D0")]
    public int initialResistSleep;
    [Token(Token = "0x400DA6C")]
    [FieldOffset(Offset = "0x1D4")]
    public int limitResistSleep;
    [Token(Token = "0x400DA6D")]
    [FieldOffset(Offset = "0x1D8")]
    public int initialResistParalysis;
    [Token(Token = "0x400DA6E")]
    [FieldOffset(Offset = "0x1DC")]
    public int limitResistParalysis;
    [Token(Token = "0x400DA6F")]
    [FieldOffset(Offset = "0x1E0")]
    public int initialResistPoison;
    [Token(Token = "0x400DA70")]
    [FieldOffset(Offset = "0x1E4")]
    public int limitResistPoison;
    [Token(Token = "0x400DA71")]
    [FieldOffset(Offset = "0x1E8")]
    public int initialResistDeadlyPoison;
    [Token(Token = "0x400DA72")]
    [FieldOffset(Offset = "0x1EC")]
    public int limitResistDeadlyPoison;
    [Token(Token = "0x400DA73")]
    [FieldOffset(Offset = "0x1F0")]
    public int initialResistBleeding;
    [Token(Token = "0x400DA74")]
    [FieldOffset(Offset = "0x1F4")]
    public int limitResistBleeding;
    [Token(Token = "0x400DA75")]
    [FieldOffset(Offset = "0x1F8")]
    public int initialResistDazzlement;
    [Token(Token = "0x400DA76")]
    [FieldOffset(Offset = "0x1FC")]
    public int limitResistDazzlement;
    [Token(Token = "0x400DA77")]
    [FieldOffset(Offset = "0x200")]
    public int initialResistDarkness;
    [Token(Token = "0x400DA78")]
    [FieldOffset(Offset = "0x204")]
    public int limitResistDarkness;
    [Token(Token = "0x400DA79")]
    [FieldOffset(Offset = "0x208")]
    public int initialResistPetrifaction;
    [Token(Token = "0x400DA7A")]
    [FieldOffset(Offset = "0x20C")]
    public int limitResistPetrifaction;
    [Token(Token = "0x400DA7B")]
    [FieldOffset(Offset = "0x210")]
    public int initialResistDontAction;
    [Token(Token = "0x400DA7C")]
    [FieldOffset(Offset = "0x214")]
    public int limitResistDontAction;
    [Token(Token = "0x400DA7D")]
    [FieldOffset(Offset = "0x218")]
    public int initialResistDontMove;
    [Token(Token = "0x400DA7E")]
    [FieldOffset(Offset = "0x21C")]
    public int limitResistDontMove;
    [Token(Token = "0x400DA7F")]
    [FieldOffset(Offset = "0x220")]
    public int initialResistDontUseSkill;
    [Token(Token = "0x400DA80")]
    [FieldOffset(Offset = "0x224")]
    public int limitResistDontUseSkill;
    [Token(Token = "0x400DA81")]
    [FieldOffset(Offset = "0x228")]
    public int initialResistDoom;
    [Token(Token = "0x400DA82")]
    [FieldOffset(Offset = "0x22C")]
    public int limitResistDoom;
    [Token(Token = "0x400DA83")]
    [FieldOffset(Offset = "0x0")]
    public static readonly AccessoryUpgradeParameter DefaultParameter;

    [Token(Token = "0x6013DB4")]
    [Address(RVA = "0x1AE5888", Offset = "0x1AE5888", VA = "0x1AE5888")]
    static AccessoryUpgradeParameter()
    {
    }
  }
}
