// Decompiled with JetBrains decompiler
// Type: UnitDetail.Customize.ParameterDetail.CorrectParameterInfo
// Assembly: Assembly-CSharp, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null
// MVID: 815152EA-6EB1-4874-BFD7-95E0AD7F491D
// Assembly location: C:\r\DummyDll\Assembly-CSharp.dll

using Il2CppDummyDll;

#nullable disable
namespace UnitDetail.Customize.ParameterDetail
{
  [Token(Token = "0x20004FD")]
  public struct CorrectParameterInfo
  {
    [Token(Token = "0x4001A68")]
    [FieldOffset(Offset = "0x0")]
    public int totalHp;
    [Token(Token = "0x4001A69")]
    [FieldOffset(Offset = "0x4")]
    public int totalPhysicsAttack;
    [Token(Token = "0x4001A6A")]
    [FieldOffset(Offset = "0x8")]
    public int totalMagicAttack;
    [Token(Token = "0x4001A6B")]
    [FieldOffset(Offset = "0xC")]
    public int totalPhysicsDefence;
    [Token(Token = "0x4001A6C")]
    [FieldOffset(Offset = "0x10")]
    public int totalMagicDefence;
    [Token(Token = "0x4001A6D")]
    [FieldOffset(Offset = "0x14")]
    public int totalHit;
    [Token(Token = "0x4001A6E")]
    [FieldOffset(Offset = "0x18")]
    public int totalAvoid;
    [Token(Token = "0x4001A6F")]
    [FieldOffset(Offset = "0x1C")]
    public int totalCritical;
    [Token(Token = "0x4001A70")]
    [FieldOffset(Offset = "0x20")]
    public int totalCriticalAvoid;
    [Token(Token = "0x4001A71")]
    [FieldOffset(Offset = "0x24")]
    public int storyHp;
    [Token(Token = "0x4001A72")]
    [FieldOffset(Offset = "0x28")]
    public int storyPhysicsAttack;
    [Token(Token = "0x4001A73")]
    [FieldOffset(Offset = "0x2C")]
    public int storyMagicAttack;
    [Token(Token = "0x4001A74")]
    [FieldOffset(Offset = "0x30")]
    public int storyPhysicsDefence;
    [Token(Token = "0x4001A75")]
    [FieldOffset(Offset = "0x34")]
    public int storyMagicDefence;
    [Token(Token = "0x4001A76")]
    [FieldOffset(Offset = "0x38")]
    public int storyHit;
    [Token(Token = "0x4001A77")]
    [FieldOffset(Offset = "0x3C")]
    public int storyAvoid;
    [Token(Token = "0x4001A78")]
    [FieldOffset(Offset = "0x40")]
    public int storyCritical;
    [Token(Token = "0x4001A79")]
    [FieldOffset(Offset = "0x44")]
    public int storyCriticalAvoid;
    [Token(Token = "0x4001A7A")]
    [FieldOffset(Offset = "0x48")]
    public int characterHp;
    [Token(Token = "0x4001A7B")]
    [FieldOffset(Offset = "0x4C")]
    public int characterPhysicsAttack;
    [Token(Token = "0x4001A7C")]
    [FieldOffset(Offset = "0x50")]
    public int characterMagicAttack;
    [Token(Token = "0x4001A7D")]
    [FieldOffset(Offset = "0x54")]
    public int characterPhysicsDefence;
    [Token(Token = "0x4001A7E")]
    [FieldOffset(Offset = "0x58")]
    public int characterMagicDefence;
    [Token(Token = "0x4001A7F")]
    [FieldOffset(Offset = "0x5C")]
    public int characterHit;
    [Token(Token = "0x4001A80")]
    [FieldOffset(Offset = "0x60")]
    public int characterAvoid;
    [Token(Token = "0x4001A81")]
    [FieldOffset(Offset = "0x64")]
    public int characterCritical;
    [Token(Token = "0x4001A82")]
    [FieldOffset(Offset = "0x68")]
    public int characterCriticalAvoid;
    [Token(Token = "0x4001A83")]
    [FieldOffset(Offset = "0x6C")]
    public int increasedHp;
    [Token(Token = "0x4001A84")]
    [FieldOffset(Offset = "0x70")]
    public int increasedPhysicsAttack;
    [Token(Token = "0x4001A85")]
    [FieldOffset(Offset = "0x74")]
    public int increasedMagicAttack;
    [Token(Token = "0x4001A86")]
    [FieldOffset(Offset = "0x78")]
    public int increasedPhysicsDefence;
    [Token(Token = "0x4001A87")]
    [FieldOffset(Offset = "0x7C")]
    public int increasedMagicDefence;
    [Token(Token = "0x4001A88")]
    [FieldOffset(Offset = "0x80")]
    public int increasedHit;
    [Token(Token = "0x4001A89")]
    [FieldOffset(Offset = "0x84")]
    public int increasedAvoid;
    [Token(Token = "0x4001A8A")]
    [FieldOffset(Offset = "0x88")]
    public int increasedCritical;
    [Token(Token = "0x4001A8B")]
    [FieldOffset(Offset = "0x8C")]
    public int increasedCriticalAvoid;
    [Token(Token = "0x4001A8C")]
    [FieldOffset(Offset = "0x90")]
    public int reflectedHp;
    [Token(Token = "0x4001A8D")]
    [FieldOffset(Offset = "0x94")]
    public int reflectedPhysicsAttack;
    [Token(Token = "0x4001A8E")]
    [FieldOffset(Offset = "0x98")]
    public int reflectedMagicAttack;
    [Token(Token = "0x4001A8F")]
    [FieldOffset(Offset = "0x9C")]
    public int reflectedPhysicsDefence;
    [Token(Token = "0x4001A90")]
    [FieldOffset(Offset = "0xA0")]
    public int reflectedMagicDefence;
    [Token(Token = "0x4001A91")]
    [FieldOffset(Offset = "0xA4")]
    public int reflectedHit;
    [Token(Token = "0x4001A92")]
    [FieldOffset(Offset = "0xA8")]
    public int reflectedAvoid;
    [Token(Token = "0x4001A93")]
    [FieldOffset(Offset = "0xAC")]
    public int reflectedCritical;
    [Token(Token = "0x4001A94")]
    [FieldOffset(Offset = "0xB0")]
    public int reflectedCriticalAvoid;
    [Token(Token = "0x4001A95")]
    [FieldOffset(Offset = "0xB4")]
    public int correctedHp;
    [Token(Token = "0x4001A96")]
    [FieldOffset(Offset = "0xB8")]
    public int correctedPhysicsAttack;
    [Token(Token = "0x4001A97")]
    [FieldOffset(Offset = "0xBC")]
    public int correctedMagicAttack;
    [Token(Token = "0x4001A98")]
    [FieldOffset(Offset = "0xC0")]
    public int correctedPhysicsDefence;
    [Token(Token = "0x4001A99")]
    [FieldOffset(Offset = "0xC4")]
    public int correctedMagicDefence;
    [Token(Token = "0x4001A9A")]
    [FieldOffset(Offset = "0xC8")]
    public int correctedHit;
    [Token(Token = "0x4001A9B")]
    [FieldOffset(Offset = "0xCC")]
    public int correctedAvoid;
    [Token(Token = "0x4001A9C")]
    [FieldOffset(Offset = "0xD0")]
    public int correctedCritical;
    [Token(Token = "0x4001A9D")]
    [FieldOffset(Offset = "0xD4")]
    public int correctedCriticalAvoid;
  }
}
